
version: 2

models:
  - name: top_terms_brazil_sp
    description: "Top Google Trends terms in SP Brazil"
    columns:
      - name: score
        description: "Term score"
        tests:
          - not_null
      - name: region_name
        description: "Region"
        tests:
          - accepted_values:
              values: ['State of São Paulo', 'São Paulo']
      - name: refresh_date
        tests:
          - is_date
      - name: country_name
        tests:
          - unique
