
version: 2

models:
  - name: top_terms_brazil_sp
    description: "Top Google Trends terms in SP Brazil"
    columns:
      - name: score
        description: "Term score"
        tests:
          - unique
          - not_null
          - dbt_utils.expression_is_true:
              expression: "TRY_CAST(refresh_date AS VARCHAR) IS NOT NULL"
